# Learning and Decision Making

## Laboratory 3: Markov decision problems

In the end of the lab, you should submit all code/answers written in the tasks marked as "Activity n. XXX", together with the corresponding outputs and any replies to specific questions posed to the e-mail <adi.tecnico@gmail.com>. Make sure that the subject is of the form [&lt;group n.&gt;] LAB &lt;lab n.&gt;.

### 1. Modeling

Consider once again the knight domain described in the Homework and which you described as a Markov decision process.

<img src="knight.png" width="200px">

Recall that:

* At each step, the knight may move in any of the four directions---up, down, left and right. 

* The movement succeeds with a 0.6 probability and fails with a 0.4 probability. When the movement fails, the knight may stay in the same cell or move to one of the immediately adjacent cells (if there is one) with equal probability.

* The goal of the knight is to save (reach) the princess and avoid the dragon.

**Throughout the lab, use $\gamma=0.99$.**

---

#### Activity 1.        

Implement your Markov decision process in Python. In particular,

* Create a list with all the states;
* Create a list with all the actions;
* For each action, define a `numpy` array with the corresponding transition probabilities;
* Define a `numpy`array with the costs. Make sure that:
    * The costs lie in the interval [0, 1]
    * The cost for standing in the princess's cell is minimal
    * The cost for standing in the dragon's cell is maximal
    * The costs for the intermediate cells are around 1/5 of those of standing in the dragon's cell

The order for the states and actions used in the transition probability and cost matrices should match that in the lists of states and actions. 

**Note**: Don't forget to import `numpy`.

---

In [1]:
import numpy as np

gamma = 0.99
states = [1,2,3,4,5,6]
actions = ['up','down','left','right']

PU = np.array([[0.8,0.1,0,0.1,0,0],
               [0.1,0.7,0.1,0,0.1,0],
               [0,0.1,0.8,0,0,0.1],
               [0.6,0,0,0.3,0.1,0],
               [0,0.6,0,0.1,0.2,0.1],
               [0,0,0.6,0,0.1,0.3]]) 

PD = np.array([[0.3,0.1,0,0.6,0,0],
               [0.1,0.2,0.1,0,0.6,0],
               [0,0.1,0.3,0,0,0.6],
               [0.1,0,0,0.8,0.1,0],
               [0,0.1,0,0.1,0.7,0.1],
               [0,0,0.1,0,0.1,0.8]])

PL = np.array([[0.8,0.1,0,0.1,0,0],
               [0.6,0.2,0.1,0,0.1,0],
               [0,0.6,0.3,0,0,0.1],
               [0.1,0,0,0.8,0.1,0],
               [0,0.1,0,0.6,0.2,0.1],
               [0,0,0.1,0,0.6,0.3]])

PR = np.array([[0.3,0.6,0,0.1,0,0],
               [0.1,0.2,0.6,0,0.1,0],
               [0,0.1,0.8,0,0,0.1],
               [0.1,0,0,0.3,0.6,0],
               [0,0.1,0,0.1,0.2,0.6],
               [0,0,0.1,0,0.1,0.8]])

C = np.array([[0.2,0.2,0.2,0.2],
              [0.2,0.2,0.2,0.2],
              [0.2,0.2,0.2,0.2],
              [0.2,0.2,0.2,0.2],
              [1,1,1,1],
              [0,0,0,0]])
print('states:', states)
print('actions:', actions)
print('Transition probabilities with action UP:\n', PU)
print('Transition probabilities with action DOWN:\n', PD)
print('Transition probabilities with action LEFT:\n', PL)
print('Transition probabilities with action RIGHT:\n', PR)
print('Costs:\n', C)

states: [1, 2, 3, 4, 5, 6]
actions: ['up', 'down', 'left', 'right']
Transition probabilities with action UP:
 [[0.8 0.1 0.  0.1 0.  0. ]
 [0.1 0.7 0.1 0.  0.1 0. ]
 [0.  0.1 0.8 0.  0.  0.1]
 [0.6 0.  0.  0.3 0.1 0. ]
 [0.  0.6 0.  0.1 0.2 0.1]
 [0.  0.  0.6 0.  0.1 0.3]]
Transition probabilities with action DOWN:
 [[0.3 0.1 0.  0.6 0.  0. ]
 [0.1 0.2 0.1 0.  0.6 0. ]
 [0.  0.1 0.3 0.  0.  0.6]
 [0.1 0.  0.  0.8 0.1 0. ]
 [0.  0.1 0.  0.1 0.7 0.1]
 [0.  0.  0.1 0.  0.1 0.8]]
Transition probabilities with action LEFT:
 [[0.8 0.1 0.  0.1 0.  0. ]
 [0.6 0.2 0.1 0.  0.1 0. ]
 [0.  0.6 0.3 0.  0.  0.1]
 [0.1 0.  0.  0.8 0.1 0. ]
 [0.  0.1 0.  0.6 0.2 0.1]
 [0.  0.  0.1 0.  0.6 0.3]]
Transition probabilities with action RIGHT:
 [[0.3 0.6 0.  0.1 0.  0. ]
 [0.1 0.2 0.6 0.  0.1 0. ]
 [0.  0.1 0.8 0.  0.  0.1]
 [0.1 0.  0.  0.3 0.6 0. ]
 [0.  0.1 0.  0.1 0.2 0.6]
 [0.  0.  0.1 0.  0.1 0.8]]
Costs:
 [[0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [1.  1.  1.  1. ]
 [

### 2. Prediction

You are now going to evaluate a given policy, computing the corresponding cost-to-go.

---

#### Activity 2.

Describe the policy that, in each state $x$, always moves the knight to the cell closest to the princess (irrespectively of the dragon). If multiple such cells exist, the knight should select randomly between the two.

For example, suppose that the knight is in cell 1. The knight should then select randomly between the actions _D_ and _R_. Conversely, suppose that the knight is in cell 4. The knight should then select actions _R_ with probability 1.

**Note:** The policy should be described as a vector with as many rows as there are states and as many columns as there are actions, where the entry _xa_ has the probability of selecting action _a_ in state _x_.

---

In [2]:
P = np.array([[0,0.5,0,0.5],
              [0,0.5,0,0.5],
              [0,1,0,0],
              [0,0,0,1],
              [0,0,0,1],
              [0,0.5,0,0.5]])

print(P)

[[0.  0.5 0.  0.5]
 [0.  0.5 0.  0.5]
 [0.  1.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  1. ]
 [0.  0.5 0.  0.5]]


---

#### Activity 3.

Compute the cost-to-go function $J^\pi$ associated with the policy from Activity 2.

---

In [3]:
cpi = np.diag(P[:,0]).dot(C[:,0]) + np.diag(P[:,1]).dot(C[:,1]) + np.diag(P[:,2]).dot(C[:,2]) + np.diag(P[:,3]).dot(C[:,3])
Ppi = np.diag(P[:,0]).dot(PU) + np.diag(P[:,1]).dot(PD) + np.diag(P[:,2]).dot(PL) + np.diag(P[:,3]).dot(PR)
J = np.linalg.inv(np.eye(6) - gamma * Ppi).dot(cpi)

print(J)

[16.26056701 15.95826371 15.28584405 16.45495016 16.42766638 15.09441121]


### 3. Control

In this section you are going to compare value and policy iteration, both in terms of time and number of iterations.

---

#### Activity 4

Show that the policy in Activity 3 is _not_ optimal: use value iteration to compute $J^*$ and show that $J^*\neq J^\pi$. Track the time and the number of iterations taken to compute $J^*$.

**Note 1:** Stop the algorithm when the error between iterations is smaller than $10^{-8}$.

**Note 2:** You may find useful the function ``time()`` from the module ``time``.

---

In [4]:
import time

gamma = 0.99
c = np.array([[0.2],[0.2],[0.2],[0.2],[1],[0]])


J = np.zeros((6,1))
err = 1
i = 0

time0 = time.time()

while err > 1e-8:
    QU = c + gamma * PU.dot(J)
    QD = c + gamma * PD.dot(J)    
    QL = c + gamma * PL.dot(J)    
    QR = c + gamma * PR.dot(J)
    Jnew = np.min((QU,QD,QL,QR), axis=0)
    err = np.linalg.norm(Jnew-J)
    i+=1
    J = Jnew

time = time.time() - time0
    
print(J)
print('time:', time)
print(i,'iterations')

[[14.06797074]
 [13.93809867]
 [13.67954678]
 [14.24800834]
 [14.74722471]
 [13.53004987]]
time: 0.04946637153625488
1726 iterations


---

#### Activity 5

Compute once again the optimal policy now using policy iteration. Track the time and number of iterations taken and compare to those of Activity 4.

**Note:** If you find that numerical errors affect your computations (especially when comparing two values/arrays) you may use the `numpy` function `isclose` with adequately set absolute and relative tolerance parameters (e.g., $10^{-8}$).

---

In [5]:
import time

gamma = 0.99

pi = np.ones((6,4)) / 2
quit = False
i=0

time0 = time.time()

while not quit:
    cpi = np.diag(pi[:,0]).dot(C[:,0]) + np.diag(pi[:,1]).dot(C[:,1]) + np.diag(pi[:,2]).dot(C[:,2]) + np.diag(pi[:,3]).dot(C[:,3])
    Ppi = np.diag(pi[:,0]).dot(PU) + np.diag(pi[:,1]).dot(PD) + np.diag(pi[:,2]).dot(PL) + np.diag(pi[:,3]).dot(PR)
    J = np.linalg.inv(np.eye(6) - gamma * Ppi).dot(cpi)
    
    QU = C[:,0] + gamma * PU.dot(J)
    QD = C[:,1] + gamma * PD.dot(J)
    QL = C[:,2] + gamma * PL.dot(J)
    QR = C[:,3] + gamma * PR.dot(J)
    
    pinew = np.zeros((6,4))
    pinew[:,0] = np.isclose(QU,np.min([QU,QD,QL,QR], axis=0), atol=1e-8,rtol=1e-8).astype(int)
    pinew[:,1] = np.isclose(QD,np.min([QU,QD,QL,QR], axis=0), atol=1e-8,rtol=1e-8).astype(int)
    pinew[:,2] = np.isclose(QL,np.min([QU,QD,QL,QR], axis=0), atol=1e-8,rtol=1e-8).astype(int)
    pinew[:,3] = np.isclose(QR,np.min([QU,QD,QL,QR], axis=0), atol=1e-8,rtol=1e-8).astype(int)
    
    pinew = pinew/np.sum(pinew, axis=1, keepdims=True)
    
    quit = (pi == pinew).all()
    pi = pinew
    i += 1

time = time.time() - time0

print(Ppi)
print(pi)
print('time: ', time)
print(i, 'iterations')

[[0.3 0.6 0.  0.1 0.  0. ]
 [0.1 0.2 0.6 0.  0.1 0. ]
 [0.  0.1 0.3 0.  0.  0.6]
 [0.6 0.  0.  0.3 0.1 0. ]
 [0.  0.1 0.  0.1 0.2 0.6]
 [0.  0.  0.1 0.  0.1 0.8]]
[[0.  0.  0.  1. ]
 [0.  0.  0.  1. ]
 [0.  1.  0.  0. ]
 [1.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.5 0.  0.5]]
time:  0.01357889175415039
4 iterations


### 4. Simulation

Finally, in this section you will check whether the theoretical computations of the cost-to-go actually correspond to the cost incurred by an agent following a policy.

---

#### Activity 6

Starting both in cell 1 and cell 5 in the figure, 

* Generate **100** trajectories of 10,000 steps each, following the optimal policy for the MDP. 
* For each trajectory, compute the accumulated (discounted) cost. 
* Compute the average cost over the 100 trajectories.
* Compare the resulting value with that computed in Activity 4 for the two states. 

** Note:** The simulation may take a bit of time, don't despair ☺️.

---

In [7]:
costs = np.empty(100)

for j in range(100):
    steps = np.empty(10000)
    pos = 1
    cost = 0
    for i in range(9999):
        move = np.random.choice(np.arange(0, 4), p=pi[pos-1])
        if move==0:
            pos = np.random.choice(np.arange(0, 6), p=PU[pos-1])+1
        elif move==1:
            pos = np.random.choice(np.arange(0, 6), p=PD[pos-1])+1
        elif move==2:
            pos = np.random.choice(np.arange(0, 6), p=PL[pos-1])+1
        elif move==3:
            pos = np.random.choice(np.arange(0, 6), p=PR[pos-1])+1
        steps[i] = pos 
        cost += c[pos-1]*(gamma**i)
    costs[j] = cost
    print(cost)
print('average cost over the 100 trajectories, starting in position 1:', np.sum(costs)/100)

costs = np.empty(100)
for j in range(100):
    steps = np.empty(10000)
    pos = 5
    cost = 0
    for i in range(9999):
        move = np.random.choice(np.arange(0, 4), p=pi[pos-1])
        #UP
        if move==0: 
            pos = np.random.choice(np.arange(0, 6), p=PU[pos-1])+1
        #DOWN
        elif move==1: 
            pos = np.random.choice(np.arange(0, 6), p=PD[pos-1])+1
        #LEFT
        elif move==2:
            pos = np.random.choice(np.arange(0, 6), p=PL[pos-1])+1
        #RIGHT
        elif move==3:
            pos = np.random.choice(np.arange(0, 6), p=PR[pos-1])+1
        steps[i] = pos 
        cost += c[pos-1]*(gamma**i)
    costs[j] = cost
    print(cost)
print('average cost over the 100 trajectories, starting in position 5:', np.sum(costs)/100)

        

[11.55159158]
[13.40646352]
[15.44399952]
[16.02201052]
[19.86223895]
[11.58139069]
[12.52111048]
[12.83181974]
[12.37736268]
[12.76509005]
[11.08552249]
[11.7209639]
[11.50228528]
[16.97914631]
[14.8370952]
[16.32069849]
[12.01617007]
[13.28339729]
[16.34170951]
[15.75545226]
[12.00616401]
[16.39147996]
[17.0008346]
[14.35234214]
[11.31783677]
[17.85310365]
[18.23467141]
[17.28963409]
[13.76359732]
[13.26173685]
[17.24287539]
[14.22979736]
[12.37529346]
[12.20886072]
[9.12377411]
[12.62317016]
[12.83816731]
[8.88887338]
[15.54991431]
[16.26717346]
[16.31043617]
[16.58296797]
[15.17728685]
[11.18039112]
[12.55914395]
[12.91856199]
[13.37432211]
[19.023165]
[10.18706892]
[17.64393517]
[11.8277175]
[17.70154734]
[11.52288607]
[15.06358478]
[11.31281158]
[14.26334509]
[16.09084674]
[13.6482082]
[9.95773585]
[12.60550909]
[11.44460976]
[16.35976283]
[13.83499994]
[12.31593929]
[11.69490821]
[9.69196874]
[13.02816828]
[19.48208873]
[10.904936]
[11.61043264]
[15.52346739]
[15.23301397]
[12.5

KeyboardInterrupt: 

The average cost over the 100 trajectories starting in cell 1 should be lower than the average cost over the 100 trajectories starting in cell 5, as expected from the costs obtained through value iteration (activity 4).

For us, this doesn't happen everytime we run the code, even though our logic is right the calculations done could be rounding in a way that justifies the ocasional wriong results we gor.